name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout source code .
        uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}}
          cache: "pnpm"
      - name: Check Node v
        run: node -v
      - name: Install Dependices
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: zip create
        run: |
          mkdir source_code
          mv * source_code/
          zip -qq -r ./build.zip source_code/
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Upload to S3
        run: |
          aws s3 cp --region ap-northeast-2 ./build.zip s3://seju-bucket/build.zip
      - name: Depoly
        run: aws deploy create-deployment
          --application-name seju-codeDeploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name seju-codeDeploy-group
          --s3-location bucket=seju-bucket,bundleType=zip,key=build.zip
